name: isar_test
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar: any
  isar_flutter_libs: any
  path_provider: ^2.0.10
  freezed_annotation: any
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  isar_generator: any
  freezed: any
  test: ^1.20.1
  path: ^1.8.1
  flutter_lints: ^2.0.1

dependency_overrides:
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  isar_generator:
    path: ../isar_generator
  test_api: ^0.4.9
