name: isar_bench
publish_to: "none"

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  isar: any
  path: ^1.8.1

dev_dependencies:
  build_runner: any
  isar_generator: any
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  isar:
    path: ../isar
  isar_generator:
    path: ../isar_generator
